version: "3.5"

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5421:5432"
    container_name: albums-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/dumps/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: server/Dockerfile
    container_name: albums-server
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://postgres@db:5432
    volumes:
      - ./backend/server:/usr/src/app/
  frontend:
    depends_on:
      - server
    build:
      context: frontend
      dockerfile: Dockerfile 
    container_name: albums-frontend
    environment: 
      BACKEND_ADDR: server
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/src:/usr/src/app/src
  
volumes:
  pgdata:
  dumps: