version: "3.5"

services:
  updater:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: updater/Dockerfile
    container_name: albums-updater
    environment:
      DB_URL: postgres://postgres@db:5432
    volumes:
      - ./backend/updater:/usr/src/app/updater