name: Run cypress

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run Cypress tests
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm run cypress
        run: npm run cypress
